# secrets.toml
[coingecko]
api_key = "CG-dkB4kfPGtRTbFEckCK7mSv3q"

[discord]
webhook_url = "https://discord.com/api/webhooks/1396989909943718040/XjYIaPBWOSlsYCsA31fCwK7iSOayFpALGlrXA8b1wpYI1O78JfN3UnsUwSDoz94v5cIZ"